// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apitest.Models
{
    public partial class MovieView
    {
        public string PrimaryTitle { get; set; }
        public string OriginalTitle { get; set; }
        public bool IsAdult { get; set; }
        public int? StartYear { get; set; }
        public bool IsOriginalTitle { get; set; }
        public string Genre { get; set; }
        public double AverageRating { get; set; }
        public string Characters { get; set; }
        public string PrimaryName { get; set; }
    }
}